name: apf
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - pytorch-cuda
  - torchaudio
  - torchvision
  - ffmpeg
  - ipykernel
  - pip:
      - datasets[audio]
      - torchcodec
      - pydub
      - faster-whisper
      - pandas
      - pyannote.audio
      - tqdm
      - underthesea
      - evaluate
      - jiwer
      - num2words